   CREATE TABLE IF NOT EXISTS users (
        user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        user_name     VARCHAR(50) NOT NULL,
        user_email    VARCHAR(50) NOT NULL,
        CONSTRAINT UQ_USER_EMAIL UNIQUE (user_name)
    );

    CREATE TABLE IF NOT EXISTS requests (
        request_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        description    VARCHAR(255) NOT NULL,
        requestor_id   INTEGER,
        FOREIGN KEY (requestor_id) REFERENCES users (user_id) ON DELETE CASCADE
    );

   CREATE TABLE IF NOT EXISTS items (
        item_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        item_name       VARCHAR(50) NOT NULL,
        description     VARCHAR(255) NOT NULL,
        is_available     BOOLEAN NOT NULL,
        owner_id        INTEGER,
        request_id      INTEGER,
        FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE,
        FOREIGN KEY (request_id) REFERENCES requests(request_id) ON DELETE CASCADE
    );

   CREATE TABLE IF NOT EXISTS bookings (
        booking_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        start_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        end_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        item_id         INTEGER NOT NULL,
        booker_id       INTEGER,
        status          VARCHAR(50),
        FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE,
        FOREIGN KEY (booker_id) REFERENCES users(user_id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS comments (
        comment_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        text           VARCHAR(1000) NOT NULL,
        item_id        INTEGER,
        author_id      INTEGER,
        created        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        FOREIGN KEY (item_id ) REFERENCES items (item_id) ON DELETE CASCADE,
        FOREIGN KEY (author_id) REFERENCES users(user_id) ON DELETE CASCADE
    );

